/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 bldspace2.glb -d -I -R 512
Files: bldspace2.glb [10.26MB] > bldspace2.glb [68.81KB] (99%)
*/

import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

const context = createContext()
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/bldspace2.glb')
  const instances = useMemo(
    () => ({
      Mesh: nodes.Mesh032_1,
      Mesh1: nodes.Mesh032_2,
      Mesh2: nodes.Mesh032_3,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props) {
  const instances = useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.Mesh />
      <instances.Mesh1 />
      <instances.Mesh2 />
    </group>
  )
}

useGLTF.preload('/models/items/bldspace2.glb')
