/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 bsspace.glb -d -i -R 512
Files: bsspace.glb [540.91KB] > bsspace-transformed.glb [24.57KB] (95%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Bldspace(props) {
  const { nodes, materials } = useGLTF('/models/bspace/bsspace.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh032_1.geometry} material={materials.PlasterPlain001_1K} />
      <mesh geometry={nodes.Mesh032_2.geometry} material={materials['PlasterPlain001_1K.001']} />
      <mesh geometry={nodes.Mesh032_3.geometry} material={materials.brickx} />
      <mesh geometry={nodes.Mesh032_4.geometry} material={materials.TerracottaClay001_4K} />
    </group>
  )
}

useGLTF.preload('/models/bspace/bsspace.glb')
