/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function BsB(props) {
  const { nodes, materials } = useGLTF("/bldspace2.glb");
  return (
    <group rotation={[Math.PI / 2,0,0]} {...props} dispose={null}>
      <group name="Scene">
        <group name="Mesh032">
          <mesh
            name="Mesh032_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh032_1.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            name="Mesh032_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh032_2.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            name="Mesh032_3"
            castShadow
            receiveShadow
            geometry={nodes.Mesh032_3.geometry}
            material={materials.TerracottaClay001_4K}
          />
          <mesh
            name="Mesh032_4"
            castShadow
            receiveShadow
            geometry={nodes.Mesh032_4.geometry}
            material={materials.PlasterPlain001_1K}
          />
          <mesh
            name="Mesh032_5"
            castShadow
            receiveShadow
            geometry={nodes.Mesh032_5.geometry}
            material={materials.MetalBronzeWorn001_4K}
          />
          <mesh
            name="Mesh032_6"
            castShadow
            receiveShadow
            geometry={nodes.Mesh032_6.geometry}
            material={materials.VeneerWhiteOakRandomMatched001_4K}
          />
          <mesh
            name="Mesh032_7"
            castShadow
            receiveShadow
            geometry={nodes.Mesh032_7.geometry}
            material={materials["PlasterPlain001_1K.001"]}
          />
          <mesh
            name="Mesh032_8"
            castShadow
            receiveShadow
            geometry={nodes.Mesh032_8.geometry}
            material={materials.BoucleBubblyRows001_1K}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/bldspace2.glb");