/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 dividertable.glb -d -I -R 512
Files: dividertable.glb [1.64MB] > dividertable.glb [125.38KB] (92%)
*/

import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

const context = createContext()
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/dividertable.glb')
  const instances = useMemo(
    () => ({
      Object: nodes.Object_2,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props) {
  const instances = useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.Object scale={0.917} />
    </group>
  )
}

useGLTF.preload('/models/items/dividertable.glb')
