/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 duckymomo.glb -d -I -R 512
Files: duckymomo.glb [7.48MB] > duckymomo.glb [1.52MB] (80%)
*/

import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

const context = createContext()
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/duckymomo.glb')
  const instances = useMemo(
    () => ({
      BeakLowBeakFeet: nodes.BeakLow_Beak_Feet_0_1,
      BeakLowBeakFeet1: nodes.BeakLow_Beak_Feet_0_2,
      BeakLowBeakFeet2: nodes.BeakLow_Beak_Feet_0_3,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props) {
  const instances = useContext(context)
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 0.756, 0]} scale={0.001}>
        <instances.BeakLowBeakFeet />
        <instances.BeakLowBeakFeet1 />
        <instances.BeakLowBeakFeet2 />
      </group>
    </group>
  )
}

useGLTF.preload('/models/items/duckymomo.glb')
