/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 execchair.glb -d -I -R 512
Files: execchair.glb [1.28MB] > execchair.glb [304.94KB] (76%)
*/

import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

const context = createContext()
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/execchair.glb')
  const instances = useMemo(
    () => ({
      WheelLPlambert: nodes.Wheel_LP3_lambert1_0,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props) {
  const instances = useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.WheelLPlambert position={[-7.988, 0, -0.501]} rotation={[-Math.PI, 0.492, -Math.PI]} scale={0.03} />
    </group>
  )
}

useGLTF.preload('/models/items/execchair.glb')
