/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 gamingchair.glb -d -I -R 512
Files: gamingchair.glb [16.98MB] > gamingchair.glb [3.12MB] (82%)
*/

import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

const context = createContext()
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/gamingchair.glb')
  const instances = useMemo(
    () => ({
      Cylinder: nodes.Cylinder004_1,
      Cylinder1: nodes.Cylinder004_2,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props) {
  const instances = useContext(context)
  return (
    <group {...props} dispose={null}>
      <group scale={3.093}>
        <instances.Cylinder />
        <instances.Cylinder1 />
      </group>
    </group>
  )
}

useGLTF.preload('/models/items/gamingchair.glb')
