/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 headphone.glb -d -I -R 512
Files: headphone.glb [31.24KB] > headphone.glb [4KB] (87%)
*/

import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

const context = createContext()
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/headphone.glb')
  const instances = useMemo(
    () => ({
      Object: nodes.Object_13001,
      Object1: nodes.Object_13001_1,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props) {
  const instances = useContext(context)
  return (
    <group {...props} dispose={null}>
      <group rotation={[1.44, 0, -Math.PI / 2]} scale={[-0.074, -0.012, -0.074]}>
        <instances.Object />
        <instances.Object1 />
      </group>
    </group>
  )
}

useGLTF.preload('/models/items/headphone.glb')
