/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 kb.glb -d -I -R 512
Files: kb.glb [193.99KB] > kb.glb [11.2KB] (94%)
*/

import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

const context = createContext()
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/kb.glb')
  const instances = useMemo(
    () => ({
      Object: nodes.Object_5001,
      Object1: nodes.Object_5001_1,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props) {
  const instances = useContext(context)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.442, -0.007, -0.133]}>
        <instances.Object />
        <instances.Object1 />
      </group>
    </group>
  )
}

useGLTF.preload('/models/items/kb.glb')
