/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 laptop.glb -d -I -R 512
Files: laptop.glb [1.04MB] > laptop.glb [195.14KB] (81%)
*/

import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

const context = createContext()
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/laptop.glb')
  const instances = useMemo(
    () => ({
      Cube: nodes.Cube012,
      Cube1: nodes.Cube012_1,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props) {
  const instances = useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.Cube />
      <instances.Cube1 />
    </group>
  )
}

useGLTF.preload('/models/items/laptop.glb')
