/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ldesk.glb -d -I -R 512
Files: ldesk.glb [4.06MB] > ldesk.glb [383.05KB] (91%)
*/

import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

const context = createContext()
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/ldesk.glb')
  const instances = useMemo(
    () => ({
      Ldesk: nodes.ldesk,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props) {
  const instances = useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.Ldesk />
    </group>
  )
}

useGLTF.preload('/models/items/ldesk.glb')
