/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 mdplant2.glb -d -I -R 512
Files: mdplant2.glb [122.89KB] > mdplant2.glb [19.42KB] (84%)
*/

import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

const context = createContext()
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/mdplant2.glb')
  const instances = useMemo(
    () => ({
      Object: nodes.Object_7,
      Object1: nodes.Object_7_1,
      Object2: nodes.Object_7_2,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props) {
  const instances = useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.Object />
      <instances.Object1 />
      <instances.Object2 />
    </group>
  )
}

useGLTF.preload('/models/items/mdplant2.glb')
