/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 meshchair.glb -d -I -R 512
Files: meshchair.glb [1.34MB] > meshchair.glb [179.45KB] (87%)
*/

import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

const context = createContext()
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/meshchair.glb')
  const instances = useMemo(
    () => ({
      Planeblinn: nodes.Plane002_blinn2_0_1,
      Planeblinn1: nodes.Plane002_blinn2_0_2,
      Planeblinn2: nodes.Plane002_blinn2_0_3,
      Planeblinn3: nodes.Plane002_blinn2_0_4,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props) {
  const instances = useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.Planeblinn />
      <instances.Planeblinn1 />
      <instances.Planeblinn2 />
      <instances.Planeblinn3 />
    </group>
  )
}

useGLTF.preload('/models/items/meshchair.glb')
