/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 octoplant.glb -d -I -R 512
Files: octoplant.glb [6.47MB] > octoplant.glb [649.62KB] (90%)
*/

import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

const context = createContext()
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/octoplant.glb')
  const instances = useMemo(
    () => ({
      DefaultMaterial: nodes.defaultMaterial,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props) {
  const instances = useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.DefaultMaterial />
    </group>
  )
}

useGLTF.preload('/models/items/octoplant.glb')
