/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 officechair.glb -d -I -R 512
Files: officechair.glb [746.34KB] > officechair.glb [199.13KB] (73%)
*/

import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

const context = createContext()
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/officechair.glb')
  const instances = useMemo(
    () => ({
      Mesh: nodes.Mesh,
      Mesh1: nodes.Mesh_1,
      Mesh2: nodes.Mesh_2,
      Mesh3: nodes.Mesh_3,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props) {
  const instances = useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.Mesh />
      <instances.Mesh1 />
      <instances.Mesh2 />
      <instances.Mesh3 />
    </group>
  )
}

useGLTF.preload('/models/items/officechair.glb')
