/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ps2.glb -d -I -R 512
Files: ps2.glb [152.13KB] > ps2.glb [15.15KB] (90%)
*/

import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

const context = createContext()
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/ps2.glb')
  const instances = useMemo(
    () => ({
      PlaystationvPlaystationBluePlastic: nodes.Playstation_2_v2_Playstation_2_Blue_Plastic_0,
      PlaystationvPlaystationBluePlastic1: nodes.Playstation_2_v2_Playstation_2_Blue_Plastic_0_1,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props) {
  const instances = useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.PlaystationvPlaystationBluePlastic />
      <instances.PlaystationvPlaystationBluePlastic1 />
    </group>
  )
}

useGLTF.preload('/models/items/ps2.glb')
