/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ps5.glb -d -I -R 512
Files: ps5.glb [1.52MB] > ps5.glb [199.76KB] (87%)
*/

import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

const context = createContext()
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/ps5.glb')
  const instances = useMemo(
    () => ({
      CodesconsolePScodesconsolePS: nodes.codes_console_PS5_001_codes_console_PS5_001_0,
      CodesconsolePScodesconsolePS1: nodes.codes_console_PS5_001_codes_console_PS5_001_0_1,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props) {
  const instances = useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.CodesconsolePScodesconsolePS />
      <instances.CodesconsolePScodesconsolePS1 />
    </group>
  )
}

useGLTF.preload('/models/items/ps5.glb')
