/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 rasengan.glb -d -I -R 512
Files: rasengan.glb [14.52MB] > rasengan.glb [1.14MB] (92%)
*/

import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

const context = createContext()
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/rasengan.glb')
  const instances = useMemo(
    () => ({
      Object: nodes.Object_9003,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props) {
  const instances = useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.Object position={[-3.619, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.042} />
    </group>
  )
}

useGLTF.preload('/models/items/rasengan.glb')
