/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 window.glb -d -I -R 512
Files: window.glb [2.18MB] > window.glb [319.77KB] (85%)
*/

import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

const context = createContext()
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/window.glb')
  const instances = useMemo(
    () => ({
      Cube: nodes.Cube009,
      Cube1: nodes.Cube009_1,
      Cube2: nodes.Cube009_2,
      Cube3: nodes.Cube009_3,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props) {
  const instances = useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.Cube />
      <instances.Cube1 />
      <instances.Cube2 />
      <instances.Cube3 />
    </group>
  )
}

useGLTF.preload('/models/items/window.glb')
