/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 woodtopdesk.glb -d -I -R 512
Files: woodtopdesk.glb [103.72MB] > woodtopdesk.glb [3.44MB] (97%)
*/

import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

const context = createContext()
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/woodtopdesk.glb')
  const instances = useMemo(
    () => ({
      Plane: nodes.Plane005,
      Plane1: nodes.Plane005_1,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props) {
  const instances = useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.Plane />
      <instances.Plane1 />
    </group>
  )
}

useGLTF.preload('/models/items/woodtopdesk.glb')
